[build]
  base = "client"
  command = "npm run build" # Build command for the React app
  publish = "client/build" # Correct path to the build output

[build.environment]
  REACT_APP_BASE_URL_BACKEND = "https://bogg-app.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
